[server]
headless = true
port = $PORT
enableCORS = false

[client]
# You can adjust the display options here
display = "minimal"  # Options: "auto", "minimal", "compact"

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#000000"
font = "sans serif"

# Uncomment the following lines to use a custom title and favicon
# title = "My Custom Streamlit App"
# favicon = "path/to/favicon.png"

[logger]
level = "info"  # Options: "debug", "info", "warning", "error", "critical"
